version: '3.9'
services:
  db:
    image: mysql:8.0.31
    volumes:
      - ./.docker/db/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysqladmin ping"
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_DATABASE: bbs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 1
  web:
    build:
      context: .docker/web
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./.docker/web/001-seeds-laravel.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "80:80"
    command: /bin/bash -c "/var/www/html/.docker/web/entrypoint.sh"
    working_dir: /var/www/html
    depends_on:
      db:
        condition: service_healthy
